version: '3'

services:
  db:
    container_name: db
    env_file: .env.local
    image: nierdz/mysql:1.1.11
    restart: on-failure
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --general_log=1
      --general_log_file=/var/lib/mysql/general.log
    volumes:
      - ./mysql:/var/lib/mysql:rw
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -u root -p${MYSQL_ROOT_PASSWORD} ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  wordpress:
    container_name: wordpress
    env_file: .env.local
    build:
      context: ./
    restart: on-failure
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf:/etc/nginx/conf:ro
      - ./nginx/videoalacon.local.conf:/etc/nginx/conf.d/videoalacon.local.conf:ro
      - ./nginx/stats.videoalacon.local.conf:/etc/nginx/conf.d/stats.videoalacon.local.conf:ro
      - ./php/zzz-hardening.ini:/usr/local/etc/php/conf.d/zzz-hardening.ini
      - ./php/zzz-opcache.ini:/usr/local/etc/php/conf.d/zzz-opcache.ini
      - ./php/zzz-php-fpm-tuning.conf:/usr/local/etc/php-fpm.d/zzz-php-fpm-tuning.conf
      - ./videoalacon.local+1-key.pem:/etc/nginx/videoalacon.local+1-key.pem:ro
      - ./videoalacon.local+1.pem:/etc/nginx/videoalacon.local+1.pem:ro
      - ./valc:/var/www/bedrock/web/app/themes/valc:rw
      - ./images:/var/www/bedrock/web/images:ro
      - ./uploads:/var/www/bedrock/web/app/uploads:rw
      - .env.local:/var/www/bedrock/.env:ro
      - ./matomo/config.ini.php:/var/www/matomo/config/config.ini.php:ro
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://127.0.0.1:80/fpm-status || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
