version: '3'

services:
  db:
    container_name: db
    env_file: .env.local
    image: nierdz/mysql:1.1.5
    restart: on-failure
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --general_log=1
      --general_log_file=/var/lib/mysql/general.log
    volumes:
      - ./mysql:/var/lib/mysql:rw
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -u root -p${MYSQL_ROOT_PASSWORD} ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  wordpress:
    container_name: wordpress
    env_file: .env.local
    build:
      context: ./
    restart: on-failure
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf:/etc/nginx/conf:ro
      - ./nginx/mad-rabbit.com.conf:/etc/nginx/conf.d/mad-rabbit.com.conf:ro
      - ./php/dev/zzz-hardening.ini:/usr/local/etc/php/conf.d/zzz-hardening.ini
      - ./php/dev/zzz-opcache.ini:/usr/local/etc/php/conf.d/zzz-opcache.ini
      - ./php/dev/zzz-tuning.ini:/usr/local/etc/php/conf.d/zzz-tuning.ini
      - ./mad-rabbit.local-key.pem:/etc/nginx/mad-rabbit.local-key.pem:ro
      - ./mad-rabbit.local.pem:/etc/nginx/mad-rabbit.local.pem:ro
      - ./madrabbit:/var/www/bedrock/web/app/themes/madrabbit:rw
      - ./images:/var/www/bedrock/web/images:ro
      - ./uploads:/var/www/bedrock/web/app/uploads:rw
      - .env.local:/var/www/bedrock/.env:ro
    depends_on:
      - db
    extra_hosts:
      - "mad-rabbit.local:127.0.0.1"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:80 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
