version: '3'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:11
    restart: on-failure
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql:/var/lib/mysql:rw
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -u root -p${MYSQL_ROOT_PASSWORD} ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  wordpress:
    container_name: wordpress
    build:
      context: ./
    restart: on-failure
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf:/etc/nginx/conf:ro
      - ./nginx/videoalacon.local.conf:/etc/nginx/conf.d/videoalacon.local.conf:ro
      - ./nginx/stats.videoalacon.local.conf:/etc/nginx/conf.d/stats.videoalacon.local.conf:ro
      - ./php/zzz-hardening.ini:/usr/local/etc/php/conf.d/zzz-hardening.ini
      - ./php/zzz-opcache.ini:/usr/local/etc/php/conf.d/zzz-opcache.ini
      - ./php/zzz-php-fpm-tuning.conf:/usr/local/etc/php-fpm.d/zzz-php-fpm-tuning.conf
      - ./videoalacon.local+1-key.pem:/etc/nginx/videoalacon.local+1-key.pem:ro
      - ./videoalacon.local+1.pem:/etc/nginx/videoalacon.local+1.pem:ro
      - ./valc:/var/www/bedrock/web/app/themes/valc:rw
      - ./images:/var/www/bedrock/web/images:ro
      - ./uploads:/var/www/bedrock/web/app/uploads:rw
      - .env.local:/var/www/bedrock/.env:ro
      - ./matomo/config.ini.php:/var/www/matomo/config/config.ini.php:ro
    depends_on:
      - mariadb
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://127.0.0.1:80/fpm-status || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - DB_NAME="${MYSQL_DATABASE}"
      - DB_USER="${MYSQL_USER}"
      - DB_PASSWORD="${MYSQL_PASSWORD}"
      - DB_HOST='mariadb'
      - VALC_PASSWORD="${VALC_PASSWORD}"
      - WP_ENV=${WP_ENV}
      - WP_HOME=${WP_HOME}
      - WP_SITEURL=${WP_SITEURL}
      - AUTH_KEY=${AUTH_KEY}
      - SECURE_AUTH_KEY=${SECURE_AUTH_KEY}
      - LOGGED_IN_KEY=${LOGGED_IN_KEY}
      - NONCE_KEY=${NONCE_KEY}
      - AUTH_SALT=${AUTH_SALT}
      - SECURE_AUTH_SALT=${SECURE_AUTH_SALT}
      - LOGGED_IN_SALT=${LOGGED_IN_SALT}
      - NONCE_SALT=${NONCE_SALT}
