version: '3'

services:
  db:
    container_name: db
    image: nierdz/mysql:1.1.5
    restart: always
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --general_log=1
      --general_log_file=/var/lib/mysql/general.log
    volumes:
      - ./mysql:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -u root -p${MYSQL_ROOT_PASSWORD} ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  wordpress:
    container_name: wordpress
    build:
      context: ./
    restart: always
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf:/etc/nginx/conf:ro
      - ./nginx/mad-rabbit.com.conf:/etc/nginx/conf.d/mad-rabbit.com.conf:ro
      - ./mad-rabbit.local-key.pem:/etc/nginx/mad-rabbit.local-key.pem:ro
      - ./mad-rabbit.local.pem:/etc/nginx/mad-rabbit.local.pem:ro
      - ./madrabbit:/var/www/bedrock/web/app/themes/madrabbit:rw
      - ./images:/var/www/bedrock/web/images:ro
    environment:
      TMTK_PASSWORD: ${TMTK_PASSWORD}
      WP_HOME: ${WP_HOME}
    depends_on:
      - db
