name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install dependencies
        run: python -m pip install --upgrade pip virtualenv
      - name: install dependencies
        run: |
          sudo wget -O /usr/local/bin/mkcert https://github.com/FiloSottile/mkcert/releases/download/v1.4.4/mkcert-v1.4.4-linux-amd64
          sudo chmod +x /usr/local/bin/mkcert
          make install-ci
      - name: run tests
        run: make tests
