---
name: DOCKER-BUILD

on:
  push:
    paths:
      - 'Dockerfile'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install dependencies
        run: |
          sudo wget -O /usr/local/bin/mkcert https://github.com/FiloSottile/mkcert/releases/download/v1.4.4/mkcert-v1.4.4-linux-amd64
          sudo chmod +x /usr/local/bin/mkcert
          python -m pip install --upgrade pip virtualenv
          make install-ci || make install-ci
      - name: start on fresh docker installation
        run: docker system prune --all --force --volumes
      - name: build docker image
        run: make docker-build
